title: Còdec
description: Codis comuns per una tecnologia més democràtica
url: https://www.codeccoop.org

collections:
  authors:
    output: true
  workshops:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      page: "post"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
      page: "workshop"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "ajax"
    values:
      layout: "compress"

pagination:
    enabled: true
    per_page: 5
    sort_reverse: true
    permalink: "/:num/"

autopages:
    enabled: true
    categories:
        title: ':cat posts'
        permalink: '/ajax/cat/:cat/'
    collections:
        enabled: false
        title: ':coll items'
        permalink: '/ajax/coll/:coll/'
    tags:
        enabled: false
        title: ':tag posts'
        permalink: '/ajax/tag/:tag/'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-postcss
  - uglifier

sass:
  sourcemap: never
  style: compressed

exclude: [package.json, package-lock.json, postcss.config.js, LICENSE, README.md, jekyll-cli]
