title: Còdec
description: Codis comuns per una tecnologia més democràtica
url: https://codeccoop.org

collections:
  authors:
    output: true
  workshops:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      page: "post"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
      page: "workshop"
  - scope:
      path: ""
    values:
      layout: "default"

paginate: 3
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-postcss

sass:
  sourcemap: never


