#! /usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $dir

order="$1";
options=(
	"serve"
	"serve:drafts"
	"build:pre"
	"build"
)

if [[ -z "$order" ]]; then
	echo
	echo "JEKYLL CLI"
	echo "----------"
	echo "What do you want to do?"

	i=0;
	for opt in "${options[@]}"; do
		echo "[$i]: $opt"
		i=$((i+1))
	done

	echo
	echo "Enter an option:"
	read order
	echo

	re="^[0-9]*$"
	if [[ $order =~ $re ]]; then
		order=${options[$order]}
		echo $order
	fi
fi

if [[ "$order" == "serve" ]]; then
	bundle exec jekyll serve -H 0.0.0.0 --livereload -P 8050
elif [[ "$order" == "serve:drafts" ]]; then
	bundle exec jekyll serve -H 0.0.0.0 --livereload -P 8050 --drafts
elif [[ "$order" == "build:pre" ]]; then
	bundle exec jekyll build

	echo
	echo "Build success!"
elif [[ "$order" == "build" ]]; then
	JEKYLL_ENV=production bundle exec jekyll build # --config _config.pro.yml 

	echo
	echo "Build success!"
else
	echo "Unknown command"
fi


