- id: wordpress
  name: WordPress
  subtitle: La web a les teves mans
  description: >- 
    L'arxiconegut WordPress, el gran democratitzador de la web. WordPress és un
    sistema de gestió de contingut (CMS per les inicials en anglès) que permet una gestió
    intuïtiva de webs per les usuàries que vulguin publicar i actualitzar contingut de forma
    quotidiana. Un programari madur amb un ecosistema ric en plantilles d'aparença i extensions
    funcionals que permet personalitzar la nostra pàgina de mil maneres diferents, des d'una
    botiga online a un portal de notícies. Des de Còdec l'estimem per la seva gran versatilitat
    i l'autonomia que dona a les usuàries sense necessitat de coneixement tècnic, per la facilitat
    amb què permet tenir una pàgina web funcionant, per l'amplissima comunitat que té al darrere
    i per ser un dels casos d'èxit més sonats del món del programari lliure.
- id: jekyll
  name: Jekyll
  subtitle: Pàgines web decreixentistes
  description: >-
    Dissenyat com un generador de pàgines web estàtiques, Jekyll és perfecte per pàgines amb poca
    necessitat d'actualització de continguts. El minimalisme de Jekyll no implica limitacions
    &#8212;disposa del seu propi sistema de plantilles i d'extensions funcionals&#8212; sinó
    que ofereix solucions simples a problemes per als què un CMS tradicional resultaria una
    opció sobredimensionada. El punt fort de Jekyll és que permet solucions lleugeres
    sense necessitat de preocupar-se per la seguretat, ni de bases de dades, ni d'actualitzacions
    programari, ni de velocitats de càrrega. Per últim, la seva simplicitat i lleugeresa ofereix
    les pàgines web amb el menor consum energètic del nostre catàleg.
- id: react
  name: Single-Page Application
  subtitle: Aplicacions web d'alt rendiment
  description: >-
    Aplicacions web d'alt rendiment, servides com a contingut estàtic i alimentades de dades via
    REST APIs. L'arquitectura d'aquesta aproximació al desenvolupament frontend permet la
    càrrega progressiva i optimitzada del contingut i l'augment del rendiment via computació
    distribuida. Treballant amb els <em>frameworks</em> d'última generació per al densevolupament web
    s'aconsegueix una experiència de desenvolupament molt àgil que redueix costos sense renunciar
    a cap de les possibilitats que els nous navegadors ofereixen.
- id: custom
  name: Programari a mida
  subtitle: Explora les possibilitats de l'entorn web
  description: >-
    Si tens una necessitat molt específica &#8212;un videojoc corporatiu, un visualitzador de
    dades, un sistema d'explotació d'un motor de càlcul, un editor de dades cartogràfiques,
    un sistema de transmissió de dades en temps real&#8212; proposa'ns-la i mirem com resoldre-ho.
    La web ens serveix com a interfície plàstica amb què interactuar, a través de la xarxa, amb
    la potència i versatilitat dels ordinadors convertits en servidors, ja que gairebé tots els
    dispositius digitals són capaços de comunicar-se via internet i disposen de visors de
    contingut web, independentment de sistemes operatius, models o marques. Tot el que puguis
    imaginar digitalitzat es pot convertir en aplicatiu web.
  url: https://www.codeccoop.org
  github: https://github.com/codeccoop
